services:
  hotsitetest:
    image: ${WEB_IMAGE}:${WEB_IMAGE_VERSION}
    depends_on:
      hotsitetest-api:
        condition: service_healthy
    networks:
      - hotsitetest-network
    healthcheck:
      test: ["CMD", "/app/docker/hotsitetest/app/healthcheck.sh", "http://127.0.0.1:5000"]
      retries: 10
      timeout: 10s
    ports:
      - "${HTTP_PORT}:5000"
    environment:
      SERVER_TYPE: web
      LOG_LEVEL: all
      HTTP_PORT: 5000
      BASE_URL: "${BASE_URL}"

  hotsitetest-api:
    image: ${API_IMAGE}:${API_IMAGE_VERSION}
    depends_on:
      hotsitetest-database:
        condition: service_healthy
    networks:
      - hotsitetest-network
    healthcheck:
      test: ["CMD", "/app/docker/hotsitetest/app/healthcheck.sh", "http://127.0.0.1:5001"]
      retries: 10
      timeout: 10s
    ports:
      - "${API_HTTP_PORT}:5001"
    environment:
      SERVER_TYPE: api
      LOG_LEVEL: all
      API_HTTP_PORT: 5001
      BASE_API_URL: "${BASE_API_URL}"
      DATABASE_SERVER: "hotsitetest-database"
      DATABASE_PORT: "3306"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_SCHEMA: "${DATABASE_SCHEMA}"

  hotsitetest-database:
    image: mariadb:11.6
    networks:
      - hotsitetest-network
    healthcheck:
      test: ["CMD", "mariadb-admin" ,"ping", "-h", "127.0.0.1"]
      retries: 10
      timeout: 10s
    volumes:
      - "hotsitetest-database-volume:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_SCHEMA}"
      MYSQL_USER: "${DATABASE_USERNAME}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"

volumes:
  hotsitetest-database-volume:

networks:
  hotsitetest-network: