version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  test:
    docker:
      - image: cimg/node:16.18-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            sudo npm install -g typescript typedoc mocha
            npm install
            
            cat > "./.env" \<<EOF
            HTTP_PORT=3123
            DATABASE_SERVER=localhost
            DATABASE_PORT=3310
            DATABASE_USERNAME=5NKVBAt7OrzrumQyQVs
            DATABASE_PASSWORD=1BBrZbKYRUM7oiMA5oY
            DATABASE_SCHEMA=hotstaq
            INFLUX_DATABASE_SERVER=http://localhost:8091
            INFLUX_DATABASE_USERNAME=5NKVBAt7OrzrumQyQVs
            INFLUX_DATABASE_PASSWORD=1BBrZbKYRUM7oiMA5oY
            INFLUX_DATABASE_ORG=freelight
            INFLUX_DATABASE_TOKEN=Ife0HerzHrloa32PsE4yg4ixA6j7tZFSMRhvBg7akUK2e
            INFLUX_DATABASE_SCHEMA=hotstaq
            LOGGING_LEVEL=verbose
            TESTING_DEVTOOLS=0
            TESTING_RUN_HEADLESS=1
            EOF
      - run:
          name: Build and install globally
          command: |
            npm run build
            npm run buildweb
            npm run buildwebdebug
            npm run version-check
            
            sudo npm -g install .
            
            npm run build-test-api
      - run:
          name: Check if everything built correctly
          command: |
            ls ./build/
            ls ./build-web/HotStaq.js
            ls ./build-web/HotStaq.min.js
            ls ./build-web/HotStaqTests_HelloWorldAPI.js
            ls ./build-web/HotStaqTests.js
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check Chrome Installation
          command: |
            google-chrome --version
            chromedriver --version
      # Will attempt to get this to work again later. Will be great for testing on multiple different browsers.
      # - run:
      #     name: "Prepare for Testing"
      #     command: |
      #       java -jar /usr/local/bin/selenium.jar -role hub &
      #       sleep 2
      #       java -Dwebdriver.chrome.driver="/usr/local/bin/chromedriver" -jar /usr/local/bin/selenium.jar -role node &
      # Will attempt to get this to work again later
      - run:
          name: "Test: Browsers"
          command: |
            export $(cat .env | xargs)
            mocha --timeout 5000 --colors ./build/tests/browser/**/*.js
      - run:
          name: "Test: Create"
          command: |
            export $(cat .env | xargs)
            mocha --timeout 5000 --colors ./build/tests/create/**/*.js
      - run:
          name: "Test: Generator"
          command: |
            export $(cat .env | xargs)
            mocha --timeout 5000 --colors ./build/tests/generator/**/*.js
      - run:
          name: "Test: Hotsite"
          command: |
            export $(cat .env | xargs)
            mocha --timeout 5000 --colors ./build/tests/hotsite/**/*.js
      - run:
          name: "Test: Local"
          command: |
            export $(cat .env | xargs)
            mocha --timeout 5000 --colors ./build/tests/local/**/*.js
      - run:
          name: "Test: Parsing"
          command: |
            export $(cat .env | xargs)
            mocha --timeout 5000 --colors ./build/tests/parsing/**/*.js
      - run:
          name: "Test: Server"
          command: |
            export $(cat .env | xargs)
            mocha --timeout 5000 --colors ./build/tests/server/**/*.js
  publish:
    docker:
      - image: cimg/node:lts
        environment:
          NPM_ACCESS_TOKEN: $NPM_ACCESS_TOKEN
          PUBLISH_LIBRARY: $PUBLISH_LIBRARY
          PUSH_IMAGES: $PUSH_IMAGES
          DOCKER_USERNAME: $DOCKER_USERNAME
          DOCKER_PASSWORD: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            sudo npm install -g typescript typedoc
            npm install
      - run:
          name: Build
          command: |
            npm run build
            npm run buildweb
            npm run version-check
      - run:
          name: Check if everything built correctly
          command: |
            ls ./build/
            ls ./build-web/HotStaq.js
            ls ./build-web/HotStaq.min.js
      - run:
          name: Publish library
          command: |
            if [ "$PUBLISH_LIBRARY" == "1" ]; then
              echo "//registry.npmjs.org/:_authToken=$NPM_ACCESS_TOKEN" > ./.npmrc
              npm publish --ignore-scripts
            fi
      # Don't build/push Docker images as they aren't as secure as what HotStaq itself generates for each app.
      # - run:
      #     name: Build Docker Images
      #     command: |
      #       if [ "$PUSH_IMAGES" == "1" ]; then
      #         # Build Node 18 images
      #         ./build.sh 18 0

      #         # Build Node 16 images. Node 16 is still latest for now
      #         ./build.sh 16 1
      #       fi
      # - run:
      #     name: Push Docker Images
      #     command: |
      #       if [ "$PUSH_IMAGES" == "1" ]; then
      #         echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      #         # Build Node 18 images
      #         ./push.sh 18 0

      #         # Build Node 16 images. Node 16 is still latest for now
      #         ./push.sh 16 1
      #       fi

workflows:
  version: 2
  hotstaq:
    jobs:
      - test:
          filters:
            branches:
              only: 
                - dev
                - master
      - publish:
          requires:
            - test
          filters:
            branches:
              only: 
                - master