version: "3.8"
services:
  ${HOTSITE_NAME}:
    image: ${NAMESPACE}/${HOTSITE_NAME}:latest
    networks:
      - ${HOTSITE_NAME}-network
    ${DOCKER_COMPOSE_APP_PORTS}
    environment:
      SERVER_TYPE: web
    deploy:
      replicas: 1

  ${HOTSITE_NAME}-api:
    image: ${NAMESPACE}/${HOTSITE_NAME}-api:latest
    networks:
      - ${HOTSITE_NAME}-network
    depends_on:
      - ${HOTSITE_NAME}-database
    ${DOCKER_COMPOSE_APP_API_PORTS}
    environment:
      SERVER_TYPE: api
      DATABASE_SERVER: " ${HOTSITE_NAME}-database"
      DATABASE_PORT: "3306"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_SCHEMA: "${DATABASE_SCHEMA}"
    deploy:
      replicas: 1

  ${HOTSITE_NAME}-database:
    image: mariadb:10.6
    networks:
      - ${HOTSITE_NAME}-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1"]
      retries: 10
      timeout: 10s
    volumes:
      - "${HOTSITE_NAME}-database-volume:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_USERNAME}"
      MYSQL_USER: "${DATABASE_PASSWORD}"
      MYSQL_PASSWORD: "${DATABASE_SCHEMA}"
    deploy:
      replicas: 1

volumes:
  ${HOTSITE_NAME}-database-volume:

network:
  ${HOTSITE_NAME}-network: