version: "3.8"
services:
  ${HOTSITE_NAME}:
    image: ${NAMESPACE}/${HOTSITE_NAME}:latest
    depends_on:
      ${HOTSITE_NAME}-api:
        condition: service_healthy
    networks:
      - ${HOTSITE_NAME}-network
    healthcheck:
      test: ["CMD", ${APP_CMDS} "healthcheck", "--dont-output-result", "http://127.0.0.1:${HTTP_PORT}"]
      retries: 10
      timeout: 10s
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    environment:
      SERVER_TYPE: web
      LOG_LEVEL: all
      HTTP_PORT: ${HTTP_PORT}

  ${HOTSITE_NAME}-api:
    image: ${NAMESPACE}/${HOTSITE_NAME}-api:latest
    depends_on:
      ${HOTSITE_NAME}-database:
        condition: service_healthy
    networks:
      - ${HOTSITE_NAME}-network
    healthcheck:
      test: ["CMD", ${APP_CMDS} "healthcheck", "--dont-output-result", "http://127.0.0.1:${API_HTTP_PORT}"]
      retries: 10
      timeout: 10s
    ports:
      - "${API_HTTP_PORT}:${API_HTTP_PORT}"
    environment:
      SERVER_TYPE: api
      LOG_LEVEL: all
      HTTP_PORT: ${API_HTTP_PORT}
      DATABASE_SERVER: " ${HOTSITE_NAME}-database"
      DATABASE_PORT: "3306"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_SCHEMA: "${DATABASE_SCHEMA}"

  ${HOTSITE_NAME}-database:
    image: mariadb:10.10
    networks:
      - ${HOTSITE_NAME}-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "127.0.0.1"]
      retries: 10
      timeout: 10s
    volumes:
      - "${HOTSITE_NAME}-database-volume:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_USERNAME}"
      MYSQL_USER: "${DATABASE_PASSWORD}"
      MYSQL_PASSWORD: "${DATABASE_SCHEMA}"

volumes:
  ${HOTSITE_NAME}-database-volume:

networks:
  ${HOTSITE_NAME}-network: