services:
  ${HOTSITE_NAME}:
    image: ${WEB_IMAGE}:${WEB_IMAGE_VERSION}
    depends_on:
      ${HOTSITE_NAME}-api:
        condition: service_healthy
    networks:
      - ${HOTSITE_NAME}-network
    healthcheck:
      test: ["CMD", "/app/docker/${HOTSITE_NAME}/app/healthcheck.sh", "http://127.0.0.1:${REAL_HTTP_PORT}"]
      retries: 10
      timeout: 10s
    ports:
      - "${HTTP_PORT}:${REAL_HTTP_PORT}"
    environment:
      SERVER_TYPE: web
      LOG_LEVEL: all
      HTTP_PORT: ${REAL_HTTP_PORT}
      BASE_URL: "${BASE_URL}"

  ${HOTSITE_NAME}-api:
    image: ${API_IMAGE}:${API_IMAGE_VERSION}
    depends_on:
      ${HOTSITE_NAME}-database:
        condition: service_healthy
    networks:
      - ${HOTSITE_NAME}-network
    healthcheck:
      test: ["CMD", "/app/docker/${HOTSITE_NAME}/app/healthcheck.sh", "http://127.0.0.1:${REAL_API_HTTP_PORT}"]
      retries: 10
      timeout: 10s
    ports:
      - "${API_HTTP_PORT}:${REAL_API_HTTP_PORT}"
    environment:
      SERVER_TYPE: api
      LOG_LEVEL: all
      API_HTTP_PORT: ${REAL_API_HTTP_PORT}
      BASE_API_URL: "${BASE_API_URL}"
      DATABASE_SERVER: "${HOTSITE_NAME}-database"
      DATABASE_PORT: "3306"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_SCHEMA: "${DATABASE_SCHEMA}"

  ${HOTSITE_NAME}-database:
    image: mariadb:11.6
    networks:
      - ${HOTSITE_NAME}-network
    healthcheck:
      test: ["CMD", "mariadb-admin" ,"ping", "-h", "127.0.0.1"]
      retries: 10
      timeout: 10s
    volumes:
      - "${HOTSITE_NAME}-database-volume:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_SCHEMA}"
      MYSQL_USER: "${DATABASE_USERNAME}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"

volumes:
  ${HOTSITE_NAME}-database-volume:

networks:
  ${HOTSITE_NAME}-network: