// Do not modify. Autogenerated by HotStaq.
import { HotCLI } from "hotstaq";

import { AppAPI } from "./AppAPI";

let cli: HotCLI = new HotCLI ();
cli.setup (process.argv).then (async () =>
    {
        cli.addAPI ("AppAPI", AppAPI);
        await cli.start ();
    });