// Do not modify. Autogenerated by HotStaq.
import { HotCLI } from "hotstaq";

import { AppAPI } from "./AppAPI";

let cli: HotCLI = new HotCLI ();
cli.setup (process.argv).then (async () =>
    {
        cli.apis["AppAPI"] = { importedAPIClass: AppAPI, exportedClassName: "AppAPI", path: "" };
        await cli.start ();
    });