{{- if .Values.ingress.enabled -}}
{{- $fullName := include "app.fullname" . -}}
{{- if .Values.ingress.certManager.enabled -}}
{{- if .Values.ingress.tls -}}
{{- fail "If ingress.certManager is enabled, ingress.tls cannot be used as well." -}}
{{- end -}}
{{- end -}}
{{- if .Values.app_web.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-frontend-ingress
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- if .Values.ingress.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ $fullName }}-frontend-issuer
    {{- end }}
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  {{- if .Values.ingress.certManager.enabled }}
  tls:
    - hosts:
      {{- range .Values.app_web.ingress.hosts }}
        - {{ .host | quote }}
      {{- end }}
      secretName: {{ $fullName }}-frontend-tls
  {{- end }}
  rules:
    {{- range .Values.app_web.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-frontend-service
                port:
                  number: 80
    {{- end }}
---
{{- end }}
{{- if .Values.app_api.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- if .Values.ingress.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ $fullName }}-issuer
    {{- end }}
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  {{- if .Values.ingress.certManager.enabled }}
  tls:
    - hosts:
      {{- range .Values.ingress.hosts }}
        - {{ .host | quote }}
      {{- end }}
      secretName: {{ $fullName }}-tls
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 5000
    {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-dicebear-ingress
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- if .Values.ingress.certManager.enabled }}
    cert-manager.io/cluster-issuer: {{ $fullName }}-dicebear-issuer
    {{- end }}
    kubernetes.io/ingress.class: {{ .Values.ingress.className }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  {{- if .Values.ingress.certManager.enabled }}
  tls:
    - hosts:
      {{- range .Values.dicebear.ingress.hosts }}
        - {{ .host | quote }}
      {{- end }}
      secretName: {{ $fullName }}-dicebear-tls
  {{- end }}
  rules:
    {{- range .Values.dicebear.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-dicebear-service
                port:
                  number: 3000
    {{- end }}
{{- end }}
{{- end -}}